# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.event import Event  # noqa: F401,E501
from swagger_server import util


class InlineResponse200EventInfos(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, attended_events: List[Event]=None, organized_events: List[Event]=None):  # noqa: E501
        """InlineResponse200EventInfos - a model defined in Swagger

        :param attended_events: The attended_events of this InlineResponse200EventInfos.  # noqa: E501
        :type attended_events: List[Event]
        :param organized_events: The organized_events of this InlineResponse200EventInfos.  # noqa: E501
        :type organized_events: List[Event]
        """
        self.swagger_types = {
            'attended_events': List[Event],
            'organized_events': List[Event]
        }

        self.attribute_map = {
            'attended_events': 'attended_events',
            'organized_events': 'organized_events'
        }
        self._attended_events = attended_events
        self._organized_events = organized_events

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200EventInfos':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_event_infos of this InlineResponse200EventInfos.  # noqa: E501
        :rtype: InlineResponse200EventInfos
        """
        return util.deserialize_model(dikt, cls)

    @property
    def attended_events(self) -> List[Event]:
        """Gets the attended_events of this InlineResponse200EventInfos.


        :return: The attended_events of this InlineResponse200EventInfos.
        :rtype: List[Event]
        """
        return self._attended_events

    @attended_events.setter
    def attended_events(self, attended_events: List[Event]):
        """Sets the attended_events of this InlineResponse200EventInfos.


        :param attended_events: The attended_events of this InlineResponse200EventInfos.
        :type attended_events: List[Event]
        """

        self._attended_events = attended_events

    @property
    def organized_events(self) -> List[Event]:
        """Gets the organized_events of this InlineResponse200EventInfos.


        :return: The organized_events of this InlineResponse200EventInfos.
        :rtype: List[Event]
        """
        return self._organized_events

    @organized_events.setter
    def organized_events(self, organized_events: List[Event]):
        """Sets the organized_events of this InlineResponse200EventInfos.


        :param organized_events: The organized_events of this InlineResponse200EventInfos.
        :type organized_events: List[Event]
        """

        self._organized_events = organized_events
