swagger: 2.0.0
info:
  title: Event Management API
  description: "An API for managing users, events and relationships between users and events."
  version: 1.0.0
host: localhost:5000
basePath: /api
schemes:
  - http
paths:
  /users/:
    get:
      tags: [UserCollection]
      summary: List all users
      operationId: users_get
      responses:
        "200":
          description: A list of users
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
          examples:
            application/json:
              - name: "John Doe"
                email: "john@example.com"
              - name: "Jane Smith"
                email: "jane@example.com"
        "500":
          description: Internal Server Error
    post:
      tags: [UserCollection]
      summary: Create a new user
      operationId: users_post
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/User"
          examples:
            application/json:
              name: "New User"
              email: "new@example.com"
      responses:
        "201":
          description: User Created
        "400":
          description: Bad Request
        "415":
          description: Unsupported Media Type
        "500":
          description: Internal Server Error

  /users/{user}/:
    get:
      tags: [UserItem]
      summary: Get a user by name
      operationId: users_user_get
      parameters:
        - $ref: "#/parameters/UserParam"
      responses:
        "200":
          description: A User Object
          schema:
            $ref: "#/definitions/User"
          examples:
            application/json:
              name: "Existing User"
              email: "existing@example.com"
              phone_number: "555-1234"
        "404":
          description: User Not Found
        "500":
          description: Internal Server Error
    put:
      tags: [UserItem]
      summary: Update a user
      operationId: users_user_put
      parameters:
        - $ref: "#/parameters/UserParam"
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/User"
          examples:
            application/json:
              name: "Updated User"
              email: "updated@example.com"
      responses:
        "201":
          description: User updated
        "400":
          description: Bad Request
        "404":
          description: User Not Found
        "415":
          description: Unsupported Media Type
        "500":
          description: Internal Server Error
    delete:
      tags: [UserItem]
      summary: Delete a user
      operationId: users_user_delete
      parameters:
        - $ref: "#/parameters/UserParam"
      responses:
        "204":
          description: User deleted
        "404":
          description: User Not Found
        "500":
          description: Internal Server Error

  /users/{user}/events/:
    get:
      tags: [UserEvents]
      summary: Get all events a user organized or attended
      operationId: users_user_events_get
      parameters:
        - $ref: "#/parameters/UserParam"
      responses:
        "200":
          description: List of user events
          schema:
            $ref: "#/definitions/inline_response_200"
          examples:
            application/json:
              user_name: "Event User"
              event_infos:
                organized_events:
                  - name: "Tech Conference"
                    location: "Convention Center"
                    time: "2023-09-15T09:00:00Z"
                    category: ["conference", "technology"]
                    tags: ["tech", "innovation"]
                attended_events:
                  - name: "Music Festival"
                    location: "Central Park"
                    time: "2023-08-05T18:00:00Z"
                    category: ["music", "entertainment"]
                    tags: ["summer", "outdoor"]
        "404":
          description: User Not Found
        "500":
          description: Internal Server Error
    post:
      tags: [UserEvents]
      summary: Create a new event
      operationId: users_user_events_post
      parameters:
        - $ref: "#/parameters/UserParam"
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Event"
          examples:
            application/json:
              name: "New Event"
              location: "Event Venue"
              time: "2023-10-01T12:00:00Z"
              category: ["workshop", "education"]
              tags: ["learning", "technology"]
      responses:
        "201":
          description: Event created
        "400":
          description: Bad Request
        "404":
          description: User Not Found
        "500":
          description: Internal Server Error

  /events/:
    get:
      tags: [EventCollection]
      summary: List all events
      operationId: events_get
      responses:
        "200":
          description: A list of events
          schema:
            type: array
            items:
              $ref: "#/definitions/Event"
          examples:
            application/json:
              - name: "Tech Conference"
                location: "Convention Center"
                time: "2023-09-15T09:00:00Z"
                category: ["conference", "technology"]
                tags: ["tech", "innovation"]
              - name: "Music Festival"
                location: "Central Park"
                time: "2023-08-05T18:00:00Z"
                category: ["music", "entertainment"]
                tags: ["summer", "outdoor"]
        "500":
          description: Internal Server Error
    post:
      tags: [EventCollection]
      summary: Create a new event
      operationId: events_post
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Event"
          examples:
            application/json:
              name: "New Event"
              location: "Event Venue"
              time: "2023-10-01T12:00:00Z"
              category: ["conference", "business"]
              tags: ["networking", "professional"]
      responses:
        "201":
          description: Event created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error

  /events/{event}/:
    get:
      tags: [EventItem]
      summary: Get an event by name
      operationId: events_event_get
      parameters:
        - $ref: "#/parameters/EventParam"
      responses:
        "200":
          description: An event object
          schema:
            $ref: "#/definitions/Event"
          examples:
            application/json:
              name: "Sample Event"
              location: "Event Venue"
              time: "2023-10-01T12:00:00Z"
              organizer: 1
              category: ["workshop", "education"]
              tags: ["learning", "technology"]
        "404":
          description: Event Not Found
        "500":
          description: Internal Server Error
    put:
      tags: [EventItem]
      summary: Update an event
      operationId: events_event_put
      parameters:
        - $ref: "#/parameters/EventParam"
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Event"
          examples:
            application/json:
              name: "Updated Event"
              location: "New Venue"
              time: "2023-11-01T14:00:00Z"
              category: ["conference", "technology"]
              tags: ["tech", "innovation"]
      responses:
        "200":
          description: Event updated
        "400":
          description: Bad Request
        "404":
          description: Event Not Found
        "500":
          description: Internal Server Error
    delete:
      tags: [EventItem]
      summary: Delete an event
      operationId: events_event_delete
      parameters:
        - $ref: "#/parameters/EventParam"
      responses:
        "204":
          description: Event deleted
        "404":
          description: Event Not Found
        "500":
          description: Internal Server Error

  /events/{event}/participants/{user}/:
    post:
      tags: [EventParticipants]
      summary: Add user to event participants
      operationId: events_event_participants_post
      parameters:
        - $ref: "#/parameters/EventParam"
        - $ref: "#/parameters/UserParam"
      responses:
        "201":
          description: User added to participants
        "404":
          description: User or Event Not Found
        "409":
          description: User already participating
        "500":
          description: Internal Server Error
    delete:
      tags: [EventParticipants]
      summary: Remove user from event participants
      operationId: events_event_participants_delete
      parameters:
        - $ref: "#/parameters/EventParam"
        - $ref: "#/parameters/UserParam"
      responses:
        "204":
          description: User removed from participants
        "404":
          description: User or Event Not Found
        "500":
          description: Internal Server Error

definitions:
  User:
    type: object
    required: [name, email]
    properties:
      name:
        type: string
      email:
        type: string
      phone_number:
        type: string

  Event:
    type: object
    required: [name, location, time]
    properties:
      name:
        type: string
      location:
        type: string
      time:
        type: string
        format: date-time
      organizer:
        type: integer
      description:
        type: string
      category:
        type: array
        items:
          type: string
      tags:
        type: array
        items:
          type: string

  inline_response_200:
    type: object
    properties:
      user_name:
        type: string
      event_infos:
        $ref: "#/definitions/inline_response_200_event_infos"

  inline_response_200_event_infos:
    type: object
    properties:
      attended_events:
        type: array
        items:
          $ref: "#/definitions/Event"
      organized_events:
        type: array
        items:
          $ref: "#/definitions/Event"

parameters:
  UserParam:
    name: user
    in: path
    description: Username as path parameter
    required: true
    type: string
  EventParam:
    name: event
    in: path
    description: Event name as path parameter
    required: true
    type: string